apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-udapeople-app
  labels:
    app: micro-udapeople-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-udapeople-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: micro-udapeople-app
    spec:
      containers:
      - image: einton/micro-udapeople
        imagePullPolicy: Always
        name: micro-udapeople-app
        ports:
        - containerPort: 3030
          protocol: TCP